# -*- coding: utf-8 -*-
"""Driver-Monitoring-System-YOLOv8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11x3qb9FyOy1eeVmpVV3a3qAtPt6YPluh

## Import and Install
"""

!pip install ultralytics opencv-python-headless==4.10.0.84

from ultralytics import YOLO
import cv2
from google.colab import files
from IPython.display import HTML
from base64 import b64encode

from google.colab import drive   # import the drive library
drive.mount('/content/drive')

!pip install ultralytics opencv-python-headless==4.10.0.84

from ultralytics import YOLO
import cv2
from IPython.display import HTML
from base64 import b64encode
from google.colab import drive   # ✅ Added here

"""## Path for video and Model"""

model_path = "/content/drive/MyDrive/AI ML Projects/Driver-Monitoring-System-YOLOv8/best_mobile.pt"
video_path = "/content/drive/MyDrive/AI ML Projects/Driver-Monitoring-System-YOLOv8/the-dangers-of-texting-while-driving_KFEC5yNJ.mp4"

from ultralytics import YOLO

# Load your pre-trained model
model = YOLO(model_path)
print("✅ Model loaded successfully!")

# =======================
# 1. Mount Google Drive
# =======================
from google.colab import drive
drive.mount('/content/drive')

# =======================
# 2. Install YOLOv8
# =======================
!pip install ultralytics

from ultralytics import YOLO
import os
from IPython.display import HTML
from base64 import b64encode

# =======================
# 3. Paths (Update these if needed)
# =======================
model_path = "/content/drive/MyDrive/AI ML Projects/Driver-Monitoring-System-YOLOv8/best_mobile.pt"
video_path = "/content/drive/MyDrive/AI ML Projects/Driver-Monitoring-System-YOLOv8/the-dangers-of-texting-while-driving_KFEC5yNJ.mp4"
output_dir = "/content/drive/MyDrive/AI ML Projects/Driver-Monitoring-System-YOLOv8/output"

# Create output folder if not exists
os.makedirs(output_dir, exist_ok=True)

# =======================
# 4. Load Model
# =======================
model = YOLO(model_path)

# =======================
# 5. Run Detection
# =======================
results = model.predict(
    source=video_path,       # Input video
    project=output_dir,      # Save directly to Drive folder
    name="detect_run",       # Subfolder
    save=True                # Save result video
)

print("✅ Detection completed! Check Drive folder:", output_dir + "/detect_run")

# =======================
# 6. Show Result Video in Colab
# =======================
# Find output video
result_video = None
for f in os.listdir(os.path.join(output_dir, "detect_run")):
    if f.endswith(".mp4"):
        result_video = os.path.join(output_dir, "detect_run", f)
        break

def show_video(video_path, width=640):
    mp4 = open(video_path,'rb').read()
    data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
    return HTML(f'<video width={width} controls><source src="{data_url}" type="video/mp4"></video>')

if result_video:
    display(show_video(result_video))
else:
    print(" No video file found in:", output_dir + "/detect_run")